<?php
function obtenerSolicitudesPendientes($pdo) {
    $sql = "SELECT 
    sp.ID_REGISTRO AS ID_SOLICITUD,
    CONCAT(p.NOMBRES, ' ', p.APELLIDOS) AS NOMBRE_ESTUDIANTE,
    c.NOMBRE_CARRERA AS CARRERA_PRINCIPAL,
    DATE_FORMAT(sp.FECHA_RECIBIDA, '%d/%m/%Y %H:%i') AS FECHA_DE_ENVIO,
    COALESCE(es.NOMBRE_TIPO_ESTADO, 'Pendiente') AS ESTADO
FROM 
    SOLICITUDES_PENDIENTES sp
JOIN 
    ASPIRANTES a ON sp.ID_ASPIRANTE = a.ID_ASPIRANTE
JOIN 
    PERSONAS p ON a.ID_PERSONA = p.ID_PERSONA
JOIN 
    CARRERAS_X_ASPIRANTE ca ON a.ID_ASPIRANTE = ca.ID_ASPIRANTE
JOIN 
    CARRERAS c ON ca.ID_CARRERA = c.ID_CARRERA
LEFT JOIN 
    HISTORIAL_SOLICITUDES_REVISADAS hsr ON a.ID_ASPIRANTE = hsr.ID_ASPIRANTE
LEFT JOIN 
    ESTADOS_SOLICITUDES es ON hsr.ID_ESTADO_SOLICITUD = es.ID_ESTADO_SOLICITUD
WHERE 
    ca.ID_REGISTRO = (
        SELECT MIN(ca2.ID_REGISTRO) 
        FROM CARRERAS_X_ASPIRANTE ca2 
        WHERE ca2.ID_ASPIRANTE = a.ID_ASPIRANTE
    )
ORDER BY 
    sp.FECHA_RECIBIDA DESC;";
    $stmt = $pdo->query($sql);
    return $stmt->fetchAll(PDO::FETCH_ASSOC);
}

/*
 "
        SELECT sp.ID_REGISTRO, p.NOMBRES, p.APELLIDOS, c.NOMBRE_CARRERA, sp.FECHA_RECIBIDA
        FROM SOLICITUDES_PENDIENTES sp
        JOIN ASPIRANTES a ON sp.ID_ASPIRANTE = a.ID_ASPIRANTE
        JOIN PERSONAS p ON a.ID_PERSONA = p.ID_PERSONA
        JOIN CARRERAS_X_ASPIRANTE ca ON ca.ID_ASPIRANTE = a.ID_ASPIRANTE
        JOIN CARRERAS c ON ca.ID_CARRERA = c.ID_CARRERA
    ";*/